### ISSUE TITLE
Sample app crash if you share image before share text

### ISSUE THREAD

**Issue by dtopuzov** [tjvantoll/nativescript-social-share#9]
Steps to reproduce:

Build sample app with {N} 2.0.0 (everything 2.0.0 -> CLI, runtimes, modules)
Run it and first tap "Share image" button.

Result:
```
W/System.err( 2824): com.tns.NativeScriptException:
W/System.err( 2824): Calling js method onClick failed
W/System.err( 2824): TypeError: Cannot read property 'getExternalFilesDir' of undefined
W/System.err( 2824): File: "/data/data/com.tjvantoll.demo/files/app/tns_modules/nativescript-social-share/social-share.js, line: 29, column: 40
W/System.err( 2824): StackTrace:
W/System.err( 2824):    Frame: function:'module.exports.shareImage', file:'/data/data/com.tjvantoll.demo/files/app/tns_modules/nativescript-social-share/social-share.js', line: 29, column: 41
W/System.err( 2824):    Frame: function:'exports.shareImage', file:'/data/data/com.tjvantoll.demo/files/app/main-page.js', line: 6, column: 14
W/System.err( 2824):    Frame: function:'Observable.notify', file:'/data/data/com.tjvantoll.demo/files/app/tns_modules/data/observable/observable.js', line: 155, column: 23
W/System.err( 2824):    Frame: function:'Observable._emit', file:'/data/data/com.tjvantoll.demo/files/app/tns_modules/data/observable/observable.js', line: 174, column: 18
W/System.err( 2824):    Frame: function:'_android.setOnClickListener.android.view.View.OnClickListener.onClick', file:'/data/data/com.tjvantoll.demo/files/app/tns_modules/ui/button/button.js', line: 27, column: 32
W/System.err( 2824):    at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 2824):    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
W/System.err( 2824):    at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
W/System.err( 2824):    at com.tns.Runtime.callJSMethod(Runtime.java:712)
W/System.err( 2824):    at com.tns.Runtime.callJSMethod(Runtime.java:693)
W/System.err( 2824):    at com.tns.Runtime.callJSMethod(Runtime.java:683)
W/System.err( 2824):    at com.tns.gen.android.view.View_OnClickListener_ftns_modules_ui_button_button_l21_c42__.onClick(View_OnClickListener_ftns_modules_ui_button_button_l21_c42__.java:11)
W/System.err( 2824):    at android.view.View.performClick(View.java:4780)
W/System.err( 2824):    at android.view.View$PerformClick.run(View.java:19866)
W/System.err( 2824):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 2824):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 2824):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 2824):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 2824):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2824):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 2824):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 2824):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Notes: 
If you first tap share text and then share image there is no crash.
Tested with Api19 and Api22 emulators (default emulators of Android Studio 2).

Emulator create commands:
```
%ANDROID_HOME%\tools\android create avd -n Emulator-Api19-Default -t android-19 --abi default/x86 -c 12M -f
%ANDROID_HOME%\tools\android create avd -n Emulator-Api22-Default -t android-22 --abi default/x86 -c 12M -f
```

**Comment by mada41** [comment]
any updates @tjvantoll ? i have same problem

**Comment by mada41** [comment]
i use advice from @dkallkro to change some code on the plugin. Maybe you can try https://github.com/mada41/nativescript-social-share @dtopuzov

**Comment by tjvantoll** [comment]
Hey all,

Sorry for the late response on this one.

This appears to work with f8aa71f2d900982faaed04c7b6f75b909e754cbb which I pushed out with version 1.2.0. If you hit any other issues with this let me know.
